Metrics/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 75

Metrics/ClassLength:
  Max: 2000

Metrics/AbcSize:
  Max: 69

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/PerceivedComplexity:
  Max: 18

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/WordArray:
  EnforcedStyle: brackets

Style/AsciiComments:
  Enabled: false

Style/MethodMissing:
  Enabled: false
